var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){function a(a){return $jscomp.SYMBOL_PREFIX+(a||"")+b++}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b){if(b){var c=$jscomp.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];g in c||(c[g]={});c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,g=0;g<d;g++){var e=a[g];if(b.call(c,e,g,a))return{i:g,v:e}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:a=function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:a=function(a,c){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var g=a.length;0<g&&0<c;)if(b[--c]!=a[--g])return!1;return 0>=g}},"es6","es3");window.gettext=window.gettext||function(a){return a};var devsite=window.devsite||{};window.devsite=devsite;devsite.location=window.location;devsite.reloadWindow=function(){devsite.location.reload()};devsite.confirm=function(a){return window.confirm.apply(window,arguments)};devsite.alert=function(a){return window.alert.apply(window,arguments)};devsite.setTimeout=function(a,b){return window.setTimeout.apply(window,arguments)};devsite.clearTimeout=function(a){window.clearTimeout.apply(window,arguments)};devsite.setInterval=function(a,b){return window.setInterval.apply(window,arguments)};
devsite.clearInterval=function(a){window.clearInterval.apply(window,arguments)};devsite.addEventListener=function(a,b,c){(window.addEventListener||window.attachEvent)(a,b,c)};devsite.inProd=function(){return!(!devsite.location.hostname.match(/\.google\.com$/)||devsite.location.hostname.match(/\.corp\.google\.com$/))};devsite.openWindow=window.open;devsite.devsite=devsite.devsite||{};devsite.devsite.HOSTNAME=devsite.inProd()?"//developers.google.com":"";
devsite.devsite.dialogConfig={autoOpen:!1,modal:!0,show:"fade",dialogClass:"devsite-dialog msgDialog",closeText:"",resizable:!1,draggable:!1,zIndex:9999};devsite.KD_FADE_LONG=218;devsite.KD_FADE_SHORT=130;devsite.credentialsDialog=devsite.credentialsDialog||{};devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_="Credentials Dialog";devsite.credentialsDialog.CREDENTIALS_DIALOG_SHOWN_="Credentials Dialog Shown";devsite.credentialsDialog.CREDENTIALS_DIALOG_PROJECTS_ERROR_="Credentials Dialog Projects Error";devsite.credentialsDialog.CREDENTIALS_DIALOG_PROJECTS_LOADED_="Credentials Dialog Projects Loaded";devsite.credentialsDialog.CREDENTIALS_DIALOG_CREDENTIALS_ERROR_="Credentials Dialog Credentials Error";
devsite.credentialsDialog.CREDENTIALS_DIALOG_CREDENTIALS_LOADED_="Credentials Dialog Credentials Loaded";devsite.credentialsDialog.CREDENTIALS_DIALOG_INSERT_="Credentials Dialog Successful Insert";devsite.credentialsDialog.CREDENTIALS_DIALOG_VIEW_="Credentials Dialog Successful View";devsite.credentialsDialog.addClickHandler=function(a){$(a).click($.proxy(devsite.credentialsDialog.popup));var b=gettext("Click to insert your credentials");$(a).each(function(){devsite.utils.addTooltip(this,b)})};
devsite.credentialsDialog.popup=function(a){a=a.target;var b=$(a).data("devsite-credential-type");a=new devsite.credentialsDialog.Dialog(a,b);a.init();a.show()};devsite.credentialsDialog.SPINNER_='<div>%(loading_text)s</div><div class="devsite-credentials-spinner-region"> <div class="devsite-credentials-spinner"> <div><div></div></div></div></div>';
devsite.credentialsDialog.Dialog=function(a,b){this.credentialsDialog_=document.createElement("div");this.credentialType_="oauth"==b?"oauth":"api_key";this.credentialsDialogContents_=document.createElement("div");$(this.credentialsDialogContents_).addClass("devsite-dialog-contents");this.credentialsDialog_.appendChild(this.credentialsDialogContents_);this.credentialsDialogButtons_=document.createElement("div");$(this.credentialsDialogButtons_).addClass("devsite-dialog-buttons");this.credentialsDialog_.appendChild(this.credentialsDialogButtons_);
b=document.createElement("h3");$(b).addClass("devsite-credentials-dialog-heading");$(b).text(gettext("Insert credential"));this.credentialsDialogContents_.appendChild(b);document.body.appendChild(this.credentialsDialog_);this.projectSelectDiv_=document.createElement("div");this.credentialSelectDiv_=document.createElement("div");this.messageEl_=document.createElement("p");this.credentialPlaceholderEl_=a;this.projectDropdown_=this.credentialDropdown_=null;a=document.createElement("div");$(a).addClass("devsite-credentials-dialog-selectors-region");
$(this.projectSelectDiv_).addClass("devsite-credentials-dialog-selector-region");$(this.credentialSelectDiv_).addClass("devsite-credentials-dialog-selector-region");$(a).append(this.projectSelectDiv_);$(a).append(this.credentialSelectDiv_);$(this.credentialsDialogContents_).append(a);$(this.credentialsDialogContents_).append(this.messageEl_);a=document.createElement("button");$(a).addClass("button button-white");$(a).attr("type","button");this.insertButton_=a;b=document.createElement("button");$(b).addClass("button button-white");
$(b).attr("type","button");"oauth"==this.credentialType_?$(a).text(gettext("View")):$(a).text(gettext("Insert"));$(b).text(gettext("Cancel"));"api_key"==this.credentialType_?$(a).click($.proxy(this.replaceText_,this)):"oauth"==this.credentialType_?$(a).click($.proxy(this.displayOAuthDetails_,this)):this.close();$(b).click($.proxy(this.close,this));$(this.insertButton_).prop("disabled",!0);$(this.credentialsDialogButtons_).append(b);$(this.credentialsDialogButtons_).append(a);$(this.credentialsDialog_).addClass("devsite-credentials-dialog devsite-dialog")};
devsite.credentialsDialog.Dialog.prototype.init=function(){if(devsite.devsite.USER_SIGNED_IN){var a=gettext("Loading projects...");$(this.projectSelectDiv_).html(interpolate(devsite.credentialsDialog.SPINNER_,{loading_text:a},!0));devsite.developerdata.getProjectsList($.proxy(this.addProjectSelector_,this),$.proxy(this.showLoadProjectError_,this))}else{a=gettext("%(start_link)sSign in%(end_link)s to insert your credentials.");var b="",c="",d=$("a.devsite-user-signin");1==d.length&&(b=d[0].href,b=
'<a href="'+b+'">',c="</a>");a=interpolate(a,{start_link:b,end_link:c},!0);$(this.projectSelectDiv_).html(a)}};
devsite.credentialsDialog.Dialog.prototype.showLoadProjectError_=function(){devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_PROJECTS_ERROR_);var a=gettext("Sorry. We couldn't load your projects. You can visit the %(start_link)sDevelopers Console%(end_link)s to see them.");a=interpolate(a,{start_link:'<a href="https://console.developers.google.com">',end_link:"</a>"},!0);$(this.projectSelectDiv_).html(a)};
devsite.credentialsDialog.Dialog.prototype.addProjectSelector_=function(a){$(this.projectSelectDiv_).empty();if(0==a.length){var b=gettext("You have no projects. You can create one in the %(start_link)sDevelopers Console%(end_link)s.");b=interpolate(b,{start_link:'<a href="https://console.developers.google.com">',end_link:"</a>"},!0);$(this.projectSelectDiv_).html(b)}else b=document.createElement("label"),$(b).text(gettext("Project")),$(this.projectSelectDiv_).append(b),this.projectDropdown_=b=devsite.developerdata.createProjectSelector(a,
$.proxy(this.loadCredentials_,this)),$(b).addClass("devsite-credentials-dialog-selector"),$(this.projectSelectDiv_).append(b),this.loadCredentials_();devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_PROJECTS_LOADED_,a.length)};
devsite.credentialsDialog.Dialog.prototype.loadCredentials_=function(){var a=JSON.parse($(this.projectDropdown_).val()||"[]"),b=gettext("Loading credentials...");$(this.insertButton_).prop("disabled",!0);$(this.credentialSelectDiv_).html(interpolate(devsite.credentialsDialog.SPINNER_,{loading_text:b},!0));"api_key"==this.credentialType_?devsite.developerdata.getProjectKeys(a.project_id,$.proxy(this.addCredSelector_,this),$.proxy(this.showLoadCredError_,this)):"oauth"==this.credentialType_?devsite.developerdata.getProjectClients(a.project_number,
$.proxy(this.addCredSelector_,this),$.proxy(this.showLoadCredError_,this)):this.close()};
devsite.credentialsDialog.Dialog.prototype.showLoadCredError_=function(){devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_CREDENTIALS_ERROR_);var a=gettext("Sorry. We couldn't load the credentials for this project. You can visit the %(start_link)sDevelopers Console%(end_link)s to see them.");a=interpolate(a,{start_link:'<a href="https://console.developers.google.com">',end_link:"</a>"},!0);$(this.credentialSelectDiv_).html(a)};
devsite.credentialsDialog.Dialog.prototype.addCredSelector_=function(a){$(this.credentialSelectDiv_).empty();if(jQuery.isEmptyObject(a)){var b=gettext("This project has no appropriate credentials. You can add one in the %(start_link)sDevelopers Console%(end_link)s."),c=JSON.parse($(this.projectDropdown_).val());c=c.project_number;c='<a href="https://console.developers.google.com/project/'+c.toString()+'/apiui/credential">';b=interpolate(b,{start_link:c,end_link:"</a>"},!0);$(this.credentialSelectDiv_).html(b);
$(this.insertButton_).prop("disabled",!0)}else b=document.createElement("label"),$(b).text(gettext("Credentials")),$(this.credentialSelectDiv_).append(b),b=devsite.developerdata.createCredentialSelector(a,null),$(b).addClass("devsite-credentials-dialog-selector"),$(this.credentialSelectDiv_).append(b),this.credentialDropdown_=b,"oauth"==this.credentialType_&&$(this.messageEl_).html(gettext("<b>Note:</b> For security, this credential can only be displayed in the Google API Console. You can copy and paste it from there.")),
$(this.insertButton_).prop("disabled",!1);devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_CREDENTIALS_LOADED_,Object.keys(a).length)};
devsite.credentialsDialog.Dialog.prototype.replaceText_=function(){var a=$(this.credentialDropdown_).val();$(this.credentialPlaceholderEl_).text(a);devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_INSERT_);this.close()};
devsite.credentialsDialog.Dialog.prototype.displayOAuthDetails_=function(){var a=$(this.projectDropdown_).val();a=JSON.parse(a).project_id;var b=$(this.credentialDropdown_).val();a="https://console.developers.google.com/project/"+a+"/apiui/credential/oauthclient/"+b;window.open(a);devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_VIEW_);this.close()};
devsite.credentialsDialog.Dialog.prototype.close=function(){$(this.credentialsDialog_).remove();$(devsite.utils.hideSiteMask()).unbind()};
devsite.credentialsDialog.Dialog.prototype.show=function(){devsite.analytics.trackAnalyticsEvent(devsite.credentialsDialog.CREDENTIALS_DIALOG_CATEGORY_,devsite.credentialsDialog.CREDENTIALS_DIALOG_SHOWN_);$(this.credentialsDialog_).css("display","block");var a=devsite.utils.showSiteMask();$(a).one("click",$.proxy(devsite.credentialsDialog.Dialog.prototype.close,this))};devsite.chips=devsite.chips||{};devsite.chips.AddChip=function(a,b,c,d,g,e){var f=$("<li></li>"),l=$("<a></a>");l.addClass("devsite-event-chip");d&&l.addClass("left");l.text(a);g||(g=function(a,b){b.length&&b.val(a.children("a.left").text());a.remove()});l.click(function(){g(f,b)});f.append(l);d&&(a=$("<a><span>x</span></a>"),a.addClass("devsite-event-chip right"),f.append(a),e||(e=function(a){a.remove()}),a.click(function(){e(f,b)}));c.append(f);return f};devsite=devsite||{};devsite.tag=devsite.tag||{};
devsite.tag.AutocompleteWidget=function(a,b,c,d,g){this.KEY_LEFT=37;this.KEY_RIGHT=39;this.KEY_BACKSPACE=8;this.KEY_DELETE=46;this.KEY_ENTER=13;this.KEY_COMMA=188;var e=this,f=$("#"+a);this.requireValid_=b;this.maxTags_=d;this.displayNames_=[];this.tagKeys_=[];this.autocompleteText_=[];this.nameToIndex_={};this.keyNameToIndex_={};this.parseTagData_=function(a){for(var b in a)this.displayNames_.push(b);this.displayNames_.sort();for(var c=0;c<this.displayNames_.length;c++){b=this.displayNames_[c];var e=
a[b].id,f=a[b]["private"];this.nameToIndex_[b]=c;this.keyNameToIndex_[e]=c;this.tagKeys_.push(e);b=f?"":this.getComparableDisplayName_(b);this.autocompleteText_.push(b)}};this.getComparableDisplayName_=function(a){return a.toLowerCase().replace(/google /,"")};this.init_=function(a,b){b?this.Autocomplete_(b):$.get("/tags/gettags",function(a){e.Autocomplete_(a)});for(b=0;b<a.length;b++)a[b]&&this.AddChosenTag(a[b].trim());f.focusin(function(a){$(this).addClass("focus");$(a.target).hasClass("tag-autocomplete")&&
f.children("input").focus()}).focusout(function(){f.removeClass("focus")});var c;f.click(function(){c&&(c.children().removeClass("selected"),c=null)});f.siblings(".too-many-tags").children(".max-tags").text(e.maxTags_);f.children("input").keydown(function(a){var b=a.keyCode,d=$(this).val(),g=f.siblings(".tags-not-found");a=f.siblings(".too-many-tags");var l=f.children(".chosen-tags");g.addClass("hidden");a.addClass("hidden");if(!d&&l.children().length)b==e.KEY_BACKSPACE||b==e.KEY_DELETE?c?(b=c,c=
c.next(),e.RemoveTag_(b)):b==e.KEY_BACKSPACE&&(c=l.children(":last-child")):b==e.KEY_LEFT||b==e.KEY_RIGHT?(d=":"+(b==e.KEY_LEFT?"last":"first")+"-child",c?(c.children().removeClass("selected"),c=b==e.KEY_LEFT?c.prev():c.next()):c=l.children(d)):c&&c.length&&(c.children().removeClass("selected"),c=null),c&&!c.length?c=null:c&&c.children().addClass("selected");else if(d&&(b==e.KEY_ENTER||b==e.KEY_COMMA))return e.requireValid_&&void 0==e.nameToIndex_[d]?g&&g.children(".tag-list")&&(g.children(".tag-list").text(d),
g.removeClass("hidden")):e.AddChosenTag(d),f.children("input").autocomplete("close"),!1;if(e.maxTags_&&e.GetNumberOfChosenTags_()>=e.maxTags_)return a.removeClass("hidden"),f.children("input").autocomplete("option","disabled",!0),!1})};this.getSuggestions_=function(a,b){a=a.term.toLowerCase();for(var c=[],d=[],f=0;f<e.displayNames_.length;f++)-1<e.autocompleteText_[f].indexOf(a)&&(c.push({label:e.displayNames_[f],value:e.displayNames_[f]}),d.push(e.displayNames_[f]));b(c)};this.Autocomplete_=function(a){this.parseTagData_(a);
a=f.attr("id");var b=$.Event(a+"-tags-loaded");f.trigger(b);f.children("input").autocomplete({appendTo:"#"+a,delay:50,minLength:1,select:function(a,b){e.AddChosenTag(b.item.label);return!1},source:e.getSuggestions_,focus:function(a,b){$(".ui-autocomplete").children("li").each(function(){var a=$(this);a.toggleClass("selected",a.children().text()==b.item.label)})}})};this.AddChosenTagByKeyName=function(a){a=e.keyNameToIndex_[a];void 0!=a&&(a=e.displayNames_[a],e.AddChosenTag(a))};this.AddChosenTag=
function(a){var b=f.find(".chosen-tags a.left");b=b.filter(function(){return $(this).text()===a}).parent();b.length?(b.detach(),f.children(".chosen-tags").append(b)):(b=f.children("input"),devsite.chips.AddChip(a,b,f.children(".chosen-tags"),!0));f.children("input").val("")};this.RemoveTag_=function(a){a.remove();f.children("input").autocomplete("option","disabled",!1)};this.GetTagNames=function(){var a=[],b=[],c=[];f.find(".chosen-tags").find("a.left").each(function(){c.push($(this).text())});var d=
f.find(".tag-autocomplete-input").val();d&&c.push(d);for(d=0;d<c.length;d++){var g=c[d];a.push(g);e.requireValid_&&void 0==e.nameToIndex_[g]&&b.push(g)}return b.length?(a=f.siblings(".tags-not-found"),a.children(".tag-list").text(b.join(", ")),a.removeClass("hidden"),!1):a};this.GetTagKeys=function(){var a=e.GetTagNames();if(!a)return!1;for(var b=[],c=0;c<a.length;c++){var d=e.nameToIndex_[a[c]];b.push(e.tagKeys_[d])}return b};this.ClearAllTags=function(){f.children(".chosen-tags").empty()};this.GetNumberOfChosenTags_=
function(){return f.children(".chosen-tags").children("li").length};this.init_((c||"").split(","),g);return{AddChosenTag:this.AddChosenTag,AddChosenTagByKeyName:this.AddChosenTagByKeyName,GetTagNames:this.GetTagNames,GetTagKeys:this.GetTagKeys,ClearAllTags:this.ClearAllTags}};var DateTimeFormat={},DateTimeConstants;DateTimeFormat.format=function(a,b,c){return DateTimeFormat.formatter(a,c)(b,c)};DateTimeFormat.loadLocaleSymbols=function(a){DateTimeFormat.symbols=a};DateTimeFormat.FULL_FORMAT=0;DateTimeFormat.LONG_FORMAT=1;DateTimeFormat.MEDIUM_FORMAT=2;DateTimeFormat.SHORT_FORMAT=3;DateTimeFormat.DEFAULT_FORMAT=2;DateTimeFormat.formatDate=function(a,b,c){c=DateTimeFormat.resolveSymbols_(c);return DateTimeFormat.format(c.DATEFORMATS[a],b,c)};
DateTimeFormat.getDateFormatter=function(a,b){b=DateTimeFormat.resolveSymbols_(b);return DateTimeFormat.formatter(b.DATEFORMATS[a],b)};DateTimeFormat.formatTime=function(a,b,c){c=DateTimeFormat.resolveSymbols_(c);return DateTimeFormat.format(c.TIMEFORMATS[a],b,c)};DateTimeFormat.getTimeFormatter=function(a,b){b=DateTimeFormat.resolveSymbols_(b);return DateTimeFormat.formatter(b.TIMEFORMATS[a],b)};
DateTimeFormat.formatDateTime=function(a,b,c){c=DateTimeFormat.resolveSymbols_(c);return DateTimeFormat.format(c.DATEFORMATS[a]+" "+c.TIMEFORMATS[a],b,c)};DateTimeFormat.getDateTimeFormatter=function(a,b){b=DateTimeFormat.resolveSymbols_(b);return DateTimeFormat.formatter(b.DATEFORMATS[a]+" "+b.TIMEFORMATS[a],b)};DateTimeFormat.TOKENS_=[/^'(?:[^']|'')*'/,/^(?:G+|y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|z+|Z+)/,/^[^'GyMkSEahKHcLQdmsvzZ]+/];
DateTimeFormat.formatter=function(a,b){b=DateTimeFormat.resolveSymbols_(b);for(var c=[];a;)for(var d=0;d<DateTimeFormat.TOKENS_.length;++d){var g=a.match(DateTimeFormat.TOKENS_[d]);if(g){g=g[0];a=a.substring(g.length);0==d&&("''"==g?g="'":(g=g.substring(1,g.length-1),g=g.replace(/''/,"'")));c.push({text:g,type:d});break}}return function(a){for(var d="",e=0;e<c.length;++e)if(1==c[e].type){var g=c[e].text,q=DateTimeFormat.formatFunctions_[g.charAt(0)];d+=q(g.length,a,b)}else d+=c[e].text;return d}};
DateTimeFormat.ZEROES_="0000000000000000";DateTimeFormat.zeroPaddingNumber_=function(a,b){for(a=String(a);a.length<b;)a=DateTimeFormat.ZEROES_.substring(0,Math.min(b-a.length,DateTimeFormat.ZEROES_.length))+a;return a};DateTimeFormat.formatEra_=function(a,b,c){b=0<b.getFullYear()?1:0;return 4<=a?c.ERANAMES[b]:c.ERAS[b]};DateTimeFormat.formatYear_=function(a,b){b=b.getFullYear();0>b&&(b=-b);return 2==a?DateTimeFormat.zeroPaddingNumber_(b%100,2):String(b)};
DateTimeFormat.formatMonth_=function(a,b,c){b=b.getMonth();switch(a){case 5:return c.NARROWMONTHS[b];case 4:return c.MONTHS[b];case 3:return c.SHORTMONTHS[b];default:return DateTimeFormat.zeroPaddingNumber_(b+1,a)}};DateTimeFormat.format24Hours_=function(a,b){b=b.getHours();return 0==b?DateTimeFormat.zeroPaddingNumber_(24,a):DateTimeFormat.zeroPaddingNumber_(b,a)};
DateTimeFormat.formatFractionalSeconds_=function(a,b){b=b.getTime()%1E3;if(1==a)return String(Math.round(b/100));if(2==a)return b=Math.floor(b/10),DateTimeFormat.zeroPaddingNumber_(b,2);b=DateTimeFormat.zeroPaddingNumber_(b,3);3<a&&(b+=DateTimeFormat.zeroPaddingNumber_(0,a-3));return b};DateTimeFormat.formatDayOfWeek_=function(a,b,c){b=b.getDay();return 4<=a?c.WEEKDAYS[b]:c.SHORTWEEKDAYS[b]};DateTimeFormat.formatAmPm_=function(a,b,c){return 12<=b.getHours()&&24>b.getHours()?c.AMPMS[1]:c.AMPMS[0]};
DateTimeFormat.format1To12Hours_=function(a,b){b=b.getHours()%12;return 0==b?DateTimeFormat.zeroPaddingNumber_(12,a):DateTimeFormat.zeroPaddingNumber_(b,a)};DateTimeFormat.format0To11Hours_=function(a,b){b=b.getHours()%12;return DateTimeFormat.zeroPaddingNumber_(b,a)};DateTimeFormat.format0To23Hours_=function(a,b){b=b.getHours();return DateTimeFormat.zeroPaddingNumber_(b,a)};
DateTimeFormat.formatStandaloneDay_=function(a,b,c){b=b.getDay();switch(a){case 5:return c.STANDALONENARROWWEEKDAYS[b];case 4:return c.STANDALONEWEEKDAYS[b];case 3:return c.STANDALONESHORTWEEKDAYS[b];default:return DateTimeFormat.zeroPaddingNumber_(b,1)}};
DateTimeFormat.formatStandaloneMonth_=function(a,b,c){b=b.getMonth();switch(a){case 5:return c.STANDALONENARROWMONTHS[b];case 4:return c.STANDALONEMONTHS[b];case 3:return c.STANDALONESHORTMONTHS[b];default:return DateTimeFormat.zeroPaddingNumber_(b+1,a)}};DateTimeFormat.formatQuarter_=function(a,b,c){b=Math.floor(b.getMonth()/3);return 4>a?c.SHORTQUARTERS[b]:c.QUARTERS[b]};DateTimeFormat.formatDate_=function(a,b){b=b.getDate();return DateTimeFormat.zeroPaddingNumber_(b,a)};
DateTimeFormat.formatMinutes_=function(a,b){b=b.getMinutes();return DateTimeFormat.zeroPaddingNumber_(b,a)};DateTimeFormat.formatSeconds_=function(a,b){b=b.getSeconds();return DateTimeFormat.zeroPaddingNumber_(b,a)};DateTimeFormat.formatTimeZoneRFC_=function(a,b,c){return 4>a?(a=b.getTimezoneOffset(),b="-",0>a&&(a=-a,b="+"),a=a/3*5+a%60,b+DateTimeFormat.zeroPaddingNumber_(a,4)):DateTimeFormat.appendGMT_(a,b,c)};
DateTimeFormat.appendGMT_=function(a,b){a=b.getTimezoneOffset();b="";0<a?b+="GMT-":(a=-a,b+="GMT+");b+=DateTimeFormat.zeroPaddingNumber_(a/60,2);b+=":";return b+=DateTimeFormat.zeroPaddingNumber_(a%60,2)};
DateTimeFormat.formatFunctions_={G:DateTimeFormat.formatEra_,y:DateTimeFormat.formatYear_,M:DateTimeFormat.formatMonth_,k:DateTimeFormat.format24Hours_,S:DateTimeFormat.formatFractionalSeconds_,E:DateTimeFormat.formatDayOfWeek_,a:DateTimeFormat.formatAmPm_,h:DateTimeFormat.format1To12Hours_,K:DateTimeFormat.format0To11Hours_,H:DateTimeFormat.format0To23Hours_,c:DateTimeFormat.formatStandaloneDay_,L:DateTimeFormat.formatStandaloneMonth_,Q:DateTimeFormat.formatQuarter_,d:DateTimeFormat.formatDate_,
m:DateTimeFormat.formatMinutes_,s:DateTimeFormat.formatSeconds_,v:DateTimeFormat.appendGMT_,z:DateTimeFormat.appendGMT_,Z:DateTimeFormat.formatTimeZoneRFC_};DateTimeFormat.resolveSymbols_=function(a){a||(DateTimeFormat.symbols||(DateTimeFormat.symbols=DateTimeConstants),a=DateTimeFormat.symbols);return a};devsite.events=devsite.events||{};devsite.sticky=devsite.sticky||{};
devsite.sticky.init=function(a){this.mainContent=$(".devsite-main-content");this.articleContent=$(".devsite-article-inner");0<$(".devsite-page-nav").length&&(this.navR=$(".devsite-page-nav"));0<$(".devsite-section-nav").length&&(this.navL=$(".devsite-section-nav"));this.footerOffset=this.headerHeight=this.navRLeft=0;this.siteWrapper=$(".devsite-wrapper");this.logoRow=$(".devsite-top-logo-row-wrapper-wrapper");this.topSection=$(".devsite-top-section");this.drawerSection=$(".devsite-collapsible-section");
this.breadcrumbRow=$(".devsite-site-nav-row");this.productRow=$(".devsite-product-id-row");this.tabRow=$(".devsite-doc-set-nav-row");this.bannerSection=$(".devsite-banner");this.logoRowHeight=this.logoRow.outerHeight();this.topSearch=$("#top-search");this.billboardLogo=$(".devsite-header-billboard-logo");this.billboardSearch=$(".devsite-billboard-search");this.topPlaceholder=this.topSearch.attr("search-placeholder");this.billboardPlaceholder=this.billboardSearch.attr("search-placeholder");this.devsiteTopLogoRow=
$(".devsite-top-logo-row");this.devsiteTopSectionWrapper=$(".devsite-top-section-wrapper");this.hasBillboardLogo=0<this.billboardLogo.length;this.hasBillboardSearch=0<this.billboardSearch.length;this.currentState=this.state.FULL_HEADER;this.initialMargin=parseInt(this.mainContent.css("margin-top"));devsite.sticky.calculateElementDimensions_();(this.navL||this.navR)&&this.resetNavVars(!0);$(window).load(function(){this.hasBillboardLogo&&devsite.sticky.calculateElementDimensions_();devsite.sticky.resize();
devsite.sticky.updateState();if(a)for(var b=0;b<a.length;b++)a[b]()})};
devsite.sticky.calculateElementDimensions_=function(){this.topSectionHeight=this.topSection.outerHeight()+this.logoRowHeight;this.drawerSectionHeight=this.drawerSection.outerHeight();this.tabRowHeight=0;this.tabRow.is(":visible")&&(this.tabRowHeight=this.tabRow.outerHeight());this.bannerSectionHeight=this.bannerSection.outerHeight();this.bottomMargin=this.desiredMargin=24;this.transitionalMargin=40;this.collapsingMargin=this.initialMargin-this.desiredMargin;this.collapsingHeader=this.drawerSectionHeight-
this.tabRowHeight;this.navsGetSticky=this.collapsingHeader+this.collapsingMargin+this.bannerSectionHeight;this.topSectionShort=this.topSectionHeight-this.collapsingHeader+this.desiredMargin};devsite.sticky.COLLAPSED_HEADER_HEIGHT=128;devsite.sticky.state={FULL_HEADER:1,TRANSITIONAL_HEADER:2,TRANSITIONAL_HEADER_MARGIN:3,COLLAPSED_HEADER:4,ARTICLE_BOTTOM_BOTH_NAVS:5,ARTICLE_BOTTOM_RIGHT_NAV:6,ARTICLE_BOTTOM_LEFT_NAV:7};
devsite.sticky.updateState=function(a){var b=a||devsite.sticky.getScrollTop(),c=devsite.sticky.getArticleBottom(),d=devsite.sticky.getBottomRightNav(b),g=devsite.sticky.getBottomLeftNav(b);0==b&&0<this.collapsingHeader?devsite.sticky.setState(devsite.sticky.state.FULL_HEADER,a):b<this.collapsingHeader?devsite.sticky.setState(devsite.sticky.state.TRANSITIONAL_HEADER,a):b<this.navsGetSticky?devsite.sticky.setState(devsite.sticky.state.TRANSITIONAL_HEADER_MARGIN,a):d<c&&g<c?devsite.sticky.setState(devsite.sticky.state.COLLAPSED_HEADER,
a):g>=c&&d>=c?devsite.sticky.setState(devsite.sticky.state.ARTICLE_BOTTOM_BOTH_NAVS,a):d>=c?devsite.sticky.setState(devsite.sticky.state.ARTICLE_BOTTOM_RIGHT_NAV,a):devsite.sticky.setState(devsite.sticky.state.ARTICLE_BOTTOM_LEFT_NAV,a)};devsite.sticky.getScrollTop=function(){return $(window).scrollTop()};devsite.sticky.getArticleBottom=function(){var a=this.mainContent;this.articleContent.length&&(a=this.articleContent);var b=a.offset();if(b)return b.top+a.outerHeight()};
devsite.sticky.getBottomRightNav=function(a){return this.navR?a+this.navR.outerHeight()+this.topSectionShort:0};devsite.sticky.getBottomLeftNav=function(a){return this.navL?a+this.navL.outerHeight()+this.topSectionShort:0};
devsite.sticky.setState=function(a,b){this.currentState!=a&&(this.currentState=a);if(this.navR||this.navL)this.resetNavVars(!1,b),this.navR&&devsite.sticky.updateNav(this.navR,this.headerHeight,this.footerOffset,this.navRLeft),this.navL&&devsite.sticky.updateNav(this.navL,this.headerHeight,this.footerOffset);devsite.sticky.updateHeader()};
devsite.sticky.getHeaderHeight=function(a,b){b=b||this.getScrollTop();if(a==this.state.FULL_HEADER)a=this.topSectionHeight+this.initialMargin+this.bannerSectionHeight;else if(a==this.state.TRANSITIONAL_HEADER||a==this.state.TRANSITIONAL_HEADER_MARGIN){var c=this.initialMargin;a==this.state.TRANSITIONAL_HEADER_MARGIN&&(c=this.transitionalMargin);a=this.topSectionHeight+c+this.bannerSectionHeight-b}else a=this.topSectionShort;return a};
devsite.sticky.getVisibleFooterOffset=function(a){a=a||this.getScrollTop();a=this.getArticleBottom()-a;return Math.min(a,this.viewportHeight-this.bottomMargin)};devsite.sticky.resetNavVars=function(a,b){a&&this.navR&&(this.navRLeft=this.navR.offset().left);this.viewportHeight=$(window).height();this.headerHeight=this.getHeaderHeight(this.currentState,b);this.footerOffset=this.getVisibleFooterOffset(b)};
devsite.sticky.updateNav=function(a,b,c,d){c-=b;var g=0<c?"":"none",e="fixed";d=d||"auto";if(this.currentState==this.state.FULL_HEADER||this.currentState==this.state.TRANSITIONAL_HEADER||this.currentState==this.state.TRANSITIONAL_HEADER_MARGIN)e="relative",b=0,d="auto";a.css({display:g,left:d,"max-height":c,position:e,top:b})};
devsite.sticky.moveSearchUp=function(){this.devsiteTopSectionWrapper.removeClass("devsite-billboard-search-active");this.billboardSearch.html()&&($(".devsite-popout").hasClass("devsite-popout-closed")&&this.devsiteTopLogoRow.removeClass("devsite-responsive-search-open"),this.billboardSearch.find("input").attr("placeholder",this.topPlaceholder),this.topSearch.append(this.billboardSearch.contents()),this.billboardSearch.empty());devsite.events.executeOnDemandCallbacks()};
devsite.sticky.moveSearchDown=function(){this.devsiteTopSectionWrapper.addClass("devsite-billboard-search-active");this.topSearch.html()&&(this.devsiteTopLogoRow.hasClass("devsite-responsive-search-open")||$(".devsite-popout").addClass("devsite-popout-closed"),this.topSearch.find("input").attr("placeholder",this.billboardPlaceholder),this.billboardSearch.append(this.topSearch.contents()),this.topSearch.empty());devsite.events.executeOnDemandCallbacks()};devsite.sticky.getWindowWidth_=function(){return $(window).width()};
devsite.sticky.updateHeader=function(){devsite.sticky.currentState==devsite.sticky.state.FULL_HEADER||devsite.sticky.currentState==devsite.sticky.state.TRANSITIONAL_HEADER?(this.siteWrapper.css({"margin-top":this.logoRowHeight+"px"}),this.topSection.removeClass("devsite-top-section-pinned"),this.logoRow.css({position:"fixed"}),this.drawerSection.css({"margin-top":"0"}),this.breadcrumbRow.css({visibility:"visible"}),this.productRow.css({visibility:"visible"}),this.mainContent.css({"margin-top":this.initialMargin}),
this.hasBillboardSearch&&devsite.sticky.moveSearchDown()):(this.siteWrapper.css({"margin-top":"0"}),this.topSection.addClass("devsite-top-section-pinned"),this.logoRow.css({position:"relative"}),this.drawerSection.css({"margin-top":-this.collapsingHeader+"px"}),this.breadcrumbRow.css({visibility:"hidden"}),this.productRow.css({visibility:"hidden"}),this.mainContent.css({"margin-top":this.topSectionHeight+this.initialMargin}),this.hasBillboardSearch&&devsite.sticky.moveSearchUp())};
devsite.sticky.resize=function(){this.navR&&(this.navR.css({position:"static",left:"auto"}),this.navRLeft=this.navR.offset().left);this.resetNavVars(!0);this.navL&&devsite.sticky.updateNav(this.navL,this.headerHeight,this.footerOffset);this.navR&&devsite.sticky.updateNav(this.navR,this.headerHeight,this.footerOffset,this.navRLeft)};devsite.sticky.setPageNavActive=function(a){a?(this.navR=$(".devsite-page-nav"),this.navR.show()):this.navR&&(this.navR.hide(),this.navR=null)};
devsite.sticky.addMainContentClass=function(a){$("body").addClass(a)};devsite.sticky.removeMainContentClass=function(a){$("body").removeClass(a)};devsite.sticky.getMainContentTop=function(){return Math.max(devsite.sticky.mainContent[0].getBoundingClientRect().top-devsite.sticky.topSectionShort-16,0)};devsite.anchors=devsite.anchors||{};devsite.anchors.tabbedHeaders_=[];devsite.anchors.init=function(){for(var a=document.querySelectorAll(".kd-tabbed-horz header[id], .kd-tabbed-vert header[id]"),b=0;b<a.length;b++)devsite.anchors.tabbedHeaders_.push("#"+a[b].id);$('a[href*="#"]:not([href="#"])').click(devsite.anchors.handleClick)};
devsite.anchors.handleClick=function(a){this.hash&&!devsite.utils.isClickEventInNewWindow(a,this)&&(-1<devsite.anchors.tabbedHeaders_.indexOf(this.hash)?devsite.anchors.jumpToLocation_(this.hash,!0):location.hostname==this.hostname&&devsite.anchors.pathsEqual_(location.pathname,this.pathname)&&(window.history.pushState({},"",this.href),devsite.anchors.jumpToLocation_(this.hash),a.preventDefault()))};
devsite.anchors.fixHashPagePositionPreLoad=function(){var a=devsite.anchors.getElementWithNameOrId_(window.location.hash),b=devsite.sticky.COLLAPSED_HEADER_HEIGHT;a&&(a.style.paddingTop=b+"px")};devsite.anchors.fixHashPagePositionPostLoad=function(){var a=devsite.anchors.getElementWithNameOrId_(window.location.hash);a&&(a.style.paddingTop="");devsite.anchors.jumpToLocation_(window.location.hash)};
devsite.anchors.jumpToLocation_=function(a,b){if(a=devsite.anchors.getElementWithNameOrId_(a))a=a.getBoundingClientRect().top+window.pageYOffset-devsite.sticky.getHeaderHeight(),b?$("html,body").animate({scrollTop:a},5):$("html,body").scrollTop(a)};devsite.anchors.getElementWithNameOrId_=function(a){if(!a)return null;a=devsite.utils.anchorIdToSelector(a);var b=document.querySelector(a);return b?b:document.querySelector('[name="'+a.slice(1)+'"]')};
devsite.anchors.pathsEqual_=function(a,b){return a.replace(/^\/|\/$|\.html$/g,"")==b.replace(/^\/|\/$|\.html$/g,"")};devsite.devsite.USER_SIGNED_IN=!1;devsite.devsite.isGoogler=!1;devsite.devsite.tenantSite="devsite";devsite.localInit=devsite.localInit||function(){};devsite.devsite.LoadFinished=function(){};devsite.devsite.CountedCallback=function(a){this.actualCallback_=a;this.count_=1};devsite.devsite.CountedCallback.prototype.count_=0;devsite.devsite.CountedCallback.prototype.actualCallback_=0;devsite.devsite.CountedCallback.prototype.GetCallback=function(){var a=this;this.count_+=1;return function(){a.finalCallback_()}};
devsite.devsite.CountedCallback.prototype.Release=function(){this.finalCallback_()};devsite.devsite.CountedCallback.prototype.finalCallback_=function(){--this.count_;0==this.count_&&this.actualCallback_()};devsite.devsite.navigateTo=function(a){a=devsite.utils.makeDevsiteUrl(a);devsite.location.href=a};devsite.devsite.whatTimeIsIt=function(){return new Date};devsite.devsite.makePath=function(a){return a};
devsite.devsite.embedForum_=function(){$("#gdf").each(function(a,b){a=$(b).data("forum");if(void 0!=a){var c=$(b).data("domain");$(b).embedForum(a,{domain:c})}})};
devsite.devsite.Init=function(a,b,c,d,g,e,f,l,h){b.ALLOWED_HOSTS.concat("youtube.com");devsite.settings.initSettings(b||{});devsite.utils.initDevsiteUtilParams(h,devsite.settings.ALLOWED_HOSTS);devsite.permissions.init(f||{});devsite.devsite.overrideJqueryGetAndPost();devsite.anchors.fixHashPagePositionPreLoad();b.SUBPATH&&!/^\/[^/]*/.test(b.SUBPATH)&&(b.SUBPATH="");e&&(devsite.devsite.USER_SIGNED_IN=!0,devsite.devsite.isGoogler=!!e.match(/@google\.com$/i));devsite.devsite.makePath=function(a){b.SUBPATH&&
a.length&&"/"==a[0]&&(a=b.SUBPATH+a);return a};b.SUBPATH&&a(document).ajaxSend(function(a,b,c){c.url=devsite.devsite.makePath(c.url)});devsite.devsite.tenantSite=b.SITE_NAME;devsite.notification.init(c);a(function(){devsite.analytics.InitAnalytics();devsite.analytics.InitAnalyticsIframes();var c=document.querySelectorAll(".devsite-section-nav, .devsite-section-nav-responsive, .devsite-nav-responsive-sidebar");if(c)for(var d=0;d<c.length;d++)devsite.Treelist.create(c[d]);devsite.devsite.RenderNativeDateTime();
devsite.devsite.InitBackendHandlers();devsite.devsite.embedForum_();a(".expandable").each(function(b,c){a(c).expandable()});devsite.multipleChoice.init();devsite.trackingQuestion.init();if(c=document.querySelector(".devsite-search-query"))c=new devsite.searchSuggest.SuggestInput(c,{projectPath:l,enableFullSiteSearch:b.FULL_SITE_SEARCH_ENABLED}),d=document.querySelectorAll(".devsite-search-form"),d=d[d.length-1],d=new devsite.Popout(d,["devsite-search-form","devsite-search-button"]),d.addClassWhenVisible(document.querySelector(".devsite-top-logo-row"),
"devsite-search-active"),c.attachTo(d),b.HISTORY_ENABLED&&!window.location.hostname.endsWith(b.SCRIPTSAFE_DOMAIN)&&(c=new devsite.history.HistoryController(!!e),c.attachTo(d));devsite.localInit();devsite.base.init(devsite.devsite.isGoogler,h,null,devsite.devsite.USER_SIGNED_IN);devsite.header.init();devsite.kennedy.InitializeSelects()});g&&devsite.devsite.initContentWidgets(d||"en",devsite.devsite.tenantSite);devsite.navigatingRadio.init();g&&(c=document.querySelector(".devsite-article-body"))&&devsite.tableOfContents.renderTableOfContents(c,
document.querySelector(".devsite-page-nav"),document.querySelector(".devsite-page-nav-embedded"));devsite.anchors.init();devsite.sticky.init([devsite.anchors.fixHashPagePositionPostLoad,devsite.navigation.init,devsite.tableOfContents.initContentState]);devsite.events.registerWindowResizeCallback(function(){var b=a(window).width(),c=a(window).height();devsite.sticky.viewportWidth==b&&devsite.sticky.viewportHeight==c||devsite.sticky.resize()});devsite.events.registerContentMutationCallback(function(){devsite.sticky.resize()});
a(window).scroll(function(){var b=a(window).scrollTop();devsite.sticky.updateState(b);g&&(devsite.tableOfContents.checkContentState(document.querySelector(".devsite-page-nav"),b),devsite.amountViewed.setMaxViewed(b));if(devsite.apix)devsite.apix.onScroll(b)})};
devsite.devsite.overrideJqueryGetAndPost=function(){$.get=function(){var a=$.get;return function(b,c,d,g){c=devsite.utils.makeDevsiteRequestData(b,c);return a(b,c,d,g)}}();$.post=function(){var a=$.post;return function(b,c,d,g){b=devsite.utils.makeDevsiteUrl(b);c=devsite.utils.makeDevsiteRequestData(b,c);return a(b,c,d,g)}}()};
devsite.devsite.initContentWidgets=function(a,b){$(document).ready(function(){$(".cp-track").cloudtrack();"cloud"==b&&jQuery.cloudtrack.trackCloudEvent();devsite.credentialsDialog.addClickHandler($(".replaceable-credential").get());devsite.framebox.Framebox.convertSrcs(a);$(".google-feedback").each(function(b,d){$(d).data("p")&&new devsite.feedback.Widget({product_id:$(d).data("p"),bucket:$(d).data("b"),context:$(d).data("context"),version:$(d).data("v")},[d],a)})})};
devsite.devsite.RenderNativeDateTime=function(a){a=a||$("body");a.find(".native-timezone").each(function(){var a=$(this).data("format")||"M/d h:mm a",c=Date.parse($(this).data("datetime"));isNaN(c)||(c=new Date(c),a=DateTimeFormat.format(a,c,{AMPMS:["a.m.","p.m."]}),$(this).html(a))});return a};devsite.devsite.InitBackendHandlers=function(){$(document).ajaxSend(setHandleXSRFHeader(document))};
devsite.devsite.getCookie=function(a,b){var c=null;if(a.cookie&&""!=a.cookie){a=a.cookie.split(";");for(var d=0;d<a.length;d++){var g=jQuery.trim(a[d]);if(g.substring(0,b.length+1)==b+"="){c=decodeURIComponent(g.substring(b.length+1));break}}}return c};devsite.devsite.deobfuscateSensitiveJson=function(a){return a.substring(4)};
function setHandleXSRFHeader(){function a(a,c,d){a=$("meta[name=xsrf_token]");a.length&&devsite.utils.isGoogleDomain(d.url)&&c.setRequestHeader("X_XSRFToken",a.attr("content"))}return a}devsite.datasection=devsite.datasection||{};devsite.datasection.init=function(){devsite.kennedy.InitializeTabbars()};/*
 
 jQuery Tools @VERSION Scrollable - New wave UI design

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/scrollable.html

 Since: March 2008
 Date: @DATE 
*/
(function(a){function b(b,c){var d=a(c);return 2>d.length?d:b.parent().find(c)}function c(c,e){var f=this,g=c.add(f),h=c.children(),q=0,t=e.vertical;d||(d=f);1<h.length&&(h=a(e.items,c));1<e.size&&(e.circular=!1);a.extend(f,{getConf:function(){return e},getIndex:function(){return q},getSize:function(){return f.getItems().size()},getNaviButtons:function(){return G.add(H)},getRoot:function(){return c},getItemWrap:function(){return h},getItems:function(){return h.find(e.item).not("."+e.clonedClass)},
move:function(a,b){return f.seekTo(q+a,b)},next:function(a){return f.move(e.size,a)},prev:function(a){return f.move(-e.size,a)},begin:function(a){return f.seekTo(0,a)},end:function(a){return f.seekTo(f.getSize()-1,a)},focus:function(){return d=f},addItem:function(b){b=a(b);e.circular?(h.children().last().before(b),h.children().first().replaceWith(b.clone().addClass(e.clonedClass))):(h.append(b),H.removeClass("disabled"));g.trigger("onAddItem",[b]);return f},seekTo:function(b,c,l){b.jquery||(b*=1);
if(e.circular&&0===b&&-1==q&&0!==c||!e.circular&&0>b||b>f.getSize()||-1>b)return f;var A=b;b.jquery?b=f.getItems().index(b):A=f.getItems().eq(b);var L=a.Event("onBeforeSeek");if(!l&&(g.trigger(L,[b,c]),L.isDefaultPrevented()||!A.length))return f;A=t?{top:-A.position().top}:{left:-A.position().left};q=b;d=f;void 0===c&&(c=e.speed);h.animate(A,c,e.easing,l||function(){g.trigger("onSeek",[b])});return f}});a.each(["onBeforeSeek","onSeek","onAddItem"],function(b,c){a.isFunction(e[c])&&a(f).bind(c,e[c]);
f[c]=function(b){b&&a(f).bind(c,b);return f}});if(e.circular){var y=f.getItems().slice(-1).clone().prependTo(h),z=f.getItems().eq(1).clone().appendTo(h);y.add(z).addClass(e.clonedClass);f.onBeforeSeek(function(a,b,c){if(!a.isDefaultPrevented()){if(-1==b)return f.seekTo(y,c,function(){f.end(0)}),a.preventDefault();b==f.getSize()&&f.seekTo(z,c,function(){f.begin(0)})}});var K=c.parents().add(c).filter(function(){if("none"===a(this).css("display"))return!0});K.length?(K.show(),f.seekTo(0,0,function(){}),
K.hide()):f.seekTo(0,0,function(){})}var G=b(c,e.prev).click(function(a){a.stopPropagation();f.prev()}),H=b(c,e.next).click(function(a){a.stopPropagation();f.next()});e.circular||(f.onBeforeSeek(function(a,b){setTimeout(function(){a.isDefaultPrevented()||(G.toggleClass(e.disabledClass,0>=b),H.toggleClass(e.disabledClass,b>=f.getSize()-1))},1)}),e.initialIndex||G.addClass(e.disabledClass));2>f.getSize()&&G.add(H).addClass(e.disabledClass);e.mousewheel&&a.fn.mousewheel&&c.mousewheel(function(a,b){if(e.mousewheel)return f.move(0>
b?1:-1,e.wheelSpeed||50),!1});if(e.touch){var I={};h[0].ontouchstart=function(a){a=a.touches[0];I.x=a.clientX;I.y=a.clientY};h[0].ontouchmove=function(a){if(1==a.touches.length&&!h.is(":animated")){var b=a.touches[0],c=I.x-b.clientX;b=I.y-b.clientY;f[t&&0<b||!t&&0<c?"next":"prev"]();a.preventDefault()}}}e.keyboard&&a(document).bind("keydown.scrollable",function(b){if(!(!e.keyboard||b.altKey||b.ctrlKey||b.metaKey||a(b.target).is(":input")||"static"!=e.keyboard&&d!=f)){var c=b.keyCode;if(t&&(38==c||
40==c))return f.move(38==c?-1:1),b.preventDefault();if(!t&&(37==c||39==c))return f.move(37==c?-1:1),b.preventDefault()}});e.initialIndex&&f.seekTo(e.initialIndex,0,function(){})}a.tools=a.tools||{version:"@VERSION"};a.tools.scrollable={conf:{activeClass:"active",circular:!1,clonedClass:"cloned",disabledClass:"disabled",easing:"swing",initialIndex:0,item:"> *",items:".items",keyboard:!0,mousewheel:!1,next:".next",prev:".prev",size:1,speed:400,vertical:!1,touch:!0,wheelSpeed:0}};var d;a.fn.scrollable=
function(b){var d=this.data("scrollable");if(d)return d;b=a.extend({},a.tools.scrollable.conf,b);this.each(function(){d=new c(a(this),b);a(this).data("scrollable",d)});return b.api?d:this}})(jQuery);/*
 
 jQuery Tools @VERSION / Scrollable Autoscroll

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/scrollable/autoscroll.html

 Since: September 2009
 Date: @DATE 
*/
(function(a){var b=a.tools.scrollable;b.autoscroll={conf:{autoplay:!0,interval:3E3,autopause:!0}};a.fn.autoscroll=function(c){"number"==typeof c&&(c={interval:c});var d=a.extend({},b.autoscroll.conf,c),g;this.each(function(){function b(){h=setTimeout(function(){c.next()},d.interval)}var c=a(this).data("scrollable"),l=c.getRoot(),h,q=!1;c&&(g=c);c.play=function(){h||(q=!1,l.bind("onSeek",b),b())};c.pause=function(){h=clearTimeout(h);l.unbind("onSeek",b)};c.resume=function(){q||c.play()};c.stop=function(){q=
!0;c.pause()};d.autopause&&l.add(c.getNaviButtons()).hover(c.pause,c.resume);d.autoplay&&c.play()});return d.api?g:this}})(jQuery);/*
 
 jQuery Tools @VERSION / Scrollable Navigator

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/scrollable/navigator.html

 Since: September 2009
 Date: @DATE 
*/
(function(a){function b(b,c){var d=a(c);return 2>d.length?d:b.parent().find(c)}var c=a.tools.scrollable;c.navigator={conf:{navi:".navi",naviItem:null,activeClass:"active",indexed:!1,idPrefix:null,history:!1}};a.fn.navigator=function(d){"string"==typeof d&&(d={navi:d});d=a.extend({},c.navigator.conf,d);var g;this.each(function(){function c(){return h.find(d.naviItem||"> *")}function f(b){var c=a("<"+(d.naviItem||"a")+"/>").click(function(c){a(this);var d=b;l.seekTo(d);c.preventDefault();y&&history.pushState({i:d})});
0===b&&c.addClass(t);d.indexed&&c.text(b+1);d.idPrefix&&c.attr("id",d.idPrefix+b);return c.appendTo(h)}var l=a(this).data("scrollable"),h=d.navi.jquery?d.navi:b(l.getRoot(),d.navi),q=l.getNaviButtons(),t=d.activeClass,y=d.history&&!!history.pushState,z=l.getConf().size;l&&(g=l);l.getNaviButtons=function(){return q.add(h)};y&&(history.pushState({i:0}),a(window).bind("popstate",function(a){(a=a.originalEvent.state)&&l.seekTo(a.i)}));c().length?c().each(function(b){a(this).click(function(c){a(this);
var d=b;l.seekTo(d);c.preventDefault();y&&history.pushState({i:d})})}):a.each(l.getItems(),function(a){0==a%z&&f(a)});l.onBeforeSeek(function(a,b){setTimeout(function(){if(!a.isDefaultPrevented()){var d=b/z,e=c().eq(d);e.length&&c().removeClass(t).eq(d).addClass(t)}},1)});l.onAddItem(function(a,b){a=l.getItems().index(b);0==a%z&&f(a)})});return d.api?g:this}})(jQuery);jQuery.cloudtrack=jQuery.cloudtrack||{};jQuery.cloudtrack.data={"try-nav":{event:{category:"GettingStarted",action:"try",label:"try-nav"},floodlight:{source:"2507573",type:"enter133",cat:"enter278"}},"try-body":{event:{category:"GettingStarted",action:"try",label:"try-body"},floodlight:{source:"2507573",type:"enter133",cat:"enter278"}},"contact-nav":{event:{category:"GettingStarted",action:"contact-sales",label:"contact-sales-nav"}},"signin-nav":{event:{category:"GettingStarted",action:"signin",label:"signin-nav"}}};
jQuery.cloudtrack.floodlight=function(a,b,c){a=encodeURIComponent(a);b=encodeURIComponent(b);c=encodeURIComponent(c);a="https://fls.doubleclick.net/activityi;src="+a+";type="+b+";cat="+c+";ord="+Math.floor(999999*Math.random())+"?";document.getElementById("DCLK_FLDiv")?b=document.getElementById("DCLK_FLDiv"):(b=document.body.appendChild(document.createElement("div")),b.id="DCLK_FLDiv",b.style.display="none");c=document.createElement("iframe");c.id="DCLK_FLIframe";c.className="floodlight-iframe";c.src=
a;b.appendChild(c)};
jQuery.fn.cloudtrack=function(){var a=jQuery.cloudtrack.data;this.each(function(){var b=0,c=$(this);c.click(function(d){var g=c.attr("id"),e=c.attr("href");"event"in a[g]&&window.dataLayer.push({"data-g-event":a[g].event.category,"data-g-action":a[g].event.action,"data-g-label":a[g].event.label,event:"autotrack-data-g"});"floodlight"in a[g]&&(jQuery.cloudtrack.floodlight(a[g].floodlight.source,a[g].floodlight.type,a[g].floodlight.cat),b=1E3);d.isDefaultPrevented()||(d.preventDefault(),setTimeout(function(){devsite.devsite.navigateTo(String(e))},
b))})});return this};jQuery.cloudtrack.escape=function(a){return a?a.replace(/\\/g,"\\\\").replace(/,/g,"\\,").replace(/=/g,"\\="):a};jQuery.cloudtrack.camelCase=function(a){return a&&-1!=a.indexOf("-")?a.toLowerCase().replace(/-+(.)?/g,function(a,c){return c?c.toUpperCase():""}):a};
jQuery.cloudtrack.stringifyMetadata=function(a){if(a){var b=[];for(g in a)b.push(g);b.sort();var c=[],d;for(d=0;d<b.length;d++){var g=b[d];var e=a[g];e&&"object"!=typeof e&&(g=jQuery.cloudtrack.camelCase(jQuery.cloudtrack.escape(g)),e=jQuery.cloudtrack.escape(String(e)),g=g+"="+e,c.push(g))}return c.join(",")}};
jQuery.cloudtrack.getMetadata=function(a){var b={};if(a)for(var c=0;c<a.attributes.length;c++){var d=a.attributes[c];if(-1!=d.name.indexOf("track-metadata-")){var g=d.name.substring(15);d=d.value;g&&d&&(b[g]=d)}}return b};
jQuery.cloudtrack.extendMetadata_=function(a,b){var c=b.attr("href");b.is("a")&&c&&(b=/^(https:\/\/)?(www\.)?console\.developers\.google\.com/g,c.match(b)&&(a.toConsole="true"),a["link-destination"]||-1==c.indexOf("console.developers.google.com")&&-1==c.indexOf("cloud.google.com")&&(a["link-destination"]=c))};
jQuery.cloudtrack.sendEventInternal_=function(a,b){if(a){var c=jQuery.cloudtrack.stringifyMetadata(a.metadata);a={event:"concordEvent",pagePath:"/"+["virtual",a.type,a.name].join("/"),eventType:a.type,eventName:a.name,realPagePath:devsite.location.pathname,metadata:c};b&&(a.eventCallback=b,a.eventTimeout="500");window.dataLayer.push(a)}};jQuery.cloudtrack.sendEvent=function(a){jQuery.cloudtrack.sendEventInternal_(a)};
jQuery.cloudtrack.trackCloudEvent=function(){$(document).click(function(a){if(a&&a.target&&window.google_tag_manager){var b=$(a.target);if((b=b.attr("track-type")?b:b.closest("[track-type]"))&&b.length&&b.attr("track-type")){var c=b.attr("href"),d=b.attr("track-type"),g=b.attr("track-name"),e=jQuery.cloudtrack.getMetadata(b[0]);jQuery.cloudtrack.extendMetadata_(e,b);var f=devsite.utils.isClickEventInNewWindow(a,b[0]);if(b.is("a")&&!a.isDefaultPrevented()&&!f&&c){a.preventDefault();var l=function(){setTimeout(function(){devsite.devsite.navigateTo(String(c))},
0)}}document.querySelector(".google-tag-manager-id")?jQuery.cloudtrack.sendEventInternal_({type:d,name:g,metadata:e},l):l()}}});return this};jQuery.gdf=jQuery.gdf||{};jQuery.gdf.options={domain:null,minHeight:390,windowPadding:150,showSearch:!0,showPopout:!0};jQuery.gdf.resize_=function(a,b,c){c=c?c:document.all?document.body.offsetHeight:window.innerHeight;a.height(Math.max(c-b.windowPadding,b.minHeight,0))};jQuery.gdf.isValidForum_=function(a){var b=/^[-+.\w]+$/i;return b.test(a)};jQuery.gdf.isValidDomain_=function(a){var b=/^([-\w]+\.)+[-\w]+$/i;return b.test(a)};
jQuery.gdf.embedForum_=function(a,b,c){jQuery.gdf.isValidForum_(b)?(b="https://groups.google.com/forum/embed/?place=forum/"+b,jQuery.gdf.isValidDomain_(c.domain)&&(b+="&domain="+c.domain),c.showSearch&&(b+="&showsearch=true"),c.showPopout&&(b+="&showpopout=true"),b+="&parenturl="+encodeURIComponent(window.location.href)):b=window.location.href;var d=jQuery("<iframe></iframe>",{src:b,scrolling:"no",frameborder:"0",width:"100%"});d.appendTo(a);jQuery.gdf.resize_(d,c);jQuery(window).bind("resize.gdf",
function(a,b){a=d;jQuery.gdf.resize_(a,c,b)})};jQuery.fn.embedForum=function(a,b){var c=jQuery.extend({},jQuery.gdf.options,b);this.each(function(b,g){b=c;jQuery.gdf.embedForum_(g,a,b)});return this};jQuery.expandable=jQuery.expandable||{};jQuery.expandable.options={controlClass:"exw-control",showalwaysClass:"showalways",expandedClass:"exw-expanded",expandedContentClass:"exw-expanded-content",expandedHtml:"&#9662;",collapsedHtml:"&#9656;",speed:100};
jQuery.expandable.buildExpandable_=function(a,b){var c=jQuery(a).find(".expand-control").eq(0);c.length||(c=jQuery("<a></a>",{"class":b.controlClass}).html(b.collapsedHtml),jQuery(a).prepend(c));c.bind("expand",function(){jQuery(this).hasClass("expand-control")||jQuery(this).html(b.expandedHtml);jQuery(this).siblings(":not(.showalways)").addClass(b.expandedContentClass);jQuery(this).hasClass("once")?jQuery(this).remove():jQuery(this).addClass(b.expandedClass)});c.bind("collapse",function(){jQuery(this).hasClass("expand-control")||
jQuery(this).html(b.collapsedHtml);jQuery(this).removeClass(b.expandedClass);jQuery(this).siblings(":not(.showalways)").removeClass(b.expandedContentClass)});c.click(function(){jQuery(this).hasClass(b.expandedClass)?jQuery(this).trigger("collapse"):jQuery(this).trigger("expand");return!1});c[0].parentNode.id&&"#"+c[0].parentNode.id==window.location.hash||c.parent().hasClass("expanded")?c.trigger("expand",null):c.trigger("collapse",null)};
jQuery.fn.expandable=function(a){var b=jQuery.extend({},jQuery.expandable.options,a);this.each(function(a,d){a=b;d&&a&&jQuery.expandable.buildExpandable_(d,a)});window.addEventListener("hashchange",function(){var a=window.location.hash;a="#"==a?"":a;a=a.replace(/[^\w\-#]/g,"_");a+=".expandable";0<jQuery(a).length&&(a=jQuery(a).find(".exw-control"),0<a.length&&a.trigger("expand",null))},!1);return this};jQuery.expandable.fromDomElement=function(a){$(a).expandable()};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(a){return a.replace(G,"&amp;").replace(H,"&lt;").replace(I,"&gt;")}function b(c,d,e){switch(c.nodeType){case 1:var f=c.tagName.toLowerCase();d.push("<",f);var g=c.attributes,k=g.length;if(k){if(e){for(var m=[],J=k;0<=--J;)m[J]=g[J];m.sort(function(a,b){return a.name<b.name?-1:a.name===b.name?0:1});g=m}for(J=0;J<k;++J)m=g[J],m.specified&&d.push(" ",m.name.toLowerCase(),'="',m.value.replace(G,"&amp;").replace(H,"&lt;").replace(I,"&gt;").replace(A,"&quot;"),'"')}d.push(">");for(g=
c.firstChild;g;g=g.nextSibling)b(g,d,e);!c.firstChild&&/^(?:br|link|img)$/.test(f)||d.push("</",f,">");break;case 3:case 4:d.push(a(c.nodeValue))}}function c(a){function b(a){if("\\"!==a.charAt(0))return a.charCodeAt(0);switch(a.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(a.substring(2),16)||a.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(a.substring(1),
8);default:return a.charCodeAt(1)}}function c(a){if(32>a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);if("\\"===a||"-"===a||"["===a||"]"===a)a="\\"+a;return a}function d(a){var d=a.substring(1,a.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);a=[];for(var e=[],g="^"===d[0],f=g?1:0,k=d.length;f<k;++f){var m=d[f];switch(m){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":a.push(m);continue}m=
b(m);if(f+2<k&&"-"===d[f+1]){var h=b(d[f+2]);f+=2}else h=m;e.push([m,h]);65>h||122<m||(65>h||90<m||e.push([Math.max(65,m)|32,Math.min(h,90)|32]),97>h||122<m||e.push([Math.max(97,m)&-33,Math.min(h,122)&-33]))}e.sort(function(a,b){return a[0]-b[0]||b[1]-a[1]});d=[];m=[NaN,NaN];for(f=0;f<e.length;++f)k=e[f],k[0]<=m[1]+1?m[1]=Math.max(m[1],k[1]):d.push(m=k);e=["["];g&&e.push("^");e.push.apply(e,a);for(f=0;f<d.length;++f)k=d[f],e.push(c(k[0])),k[1]>k[0]&&(k[1]+1>k[0]&&e.push("-"),e.push(c(k[1])));e.push("]");
return e.join("")}function e(a){for(var b=a.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),c=b.length,e=[],k=0,m=0;k<c;++k){var h=b[k];"("===h?++m:"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=m&&(e[h]=-1)}for(k=1;k<e.length;++k)-1===e[k]&&(e[k]=++g);for(m=k=0;k<c;++k)h=b[k],"("===h?(++m,void 0===e[m]&&(b[k]="(?:")):"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=m&&(b[k]="\\"+e[m]);for(m=k=0;k<c;++k)"^"===
b[k]&&"^"!==b[k+1]&&(b[k]="");if(a.ignoreCase&&f)for(k=0;k<c;++k)h=b[k],a=h.charAt(0),2<=h.length&&"["===a?b[k]=d(h):"\\"!==a&&(b[k]=h.replace(/[a-zA-Z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return b.join("")}for(var g=0,f=!1,k=!1,h=0,l=a.length;h<l;++h){var p=a[h];if(p.ignoreCase)k=!0;else if(/[a-z]/i.test(p.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){f=!0;k=!1;break}}var w=[];h=0;for(l=a.length;h<l;++h){p=a[h];if(p.global||p.multiline)throw Error(""+
p);w.push("(?:"+e(p)+")")}return new RegExp(w.join("|"),k?"gi":"g")}function d(a){var b=0;return function(c){for(var d=null,e=0,f=0,g=c.length;f<g;++f){var k=c.charAt(f);switch(k){case "\t":d||(d=[]);d.push(c.substring(e,f));e=a-b%a;for(b+=e;0<=e;e-=16)d.push("                ".substring(0,e));e=f+1;break;case "\n":b=0;break;default:++b}}if(!d)return c;d.push(c.substring(e));return d.join("")}}function g(a,b,c,d){b&&(a={source:b,basePos:a},c(a),d.push.apply(d,a.decorations))}function e(a,b){var d=
{},e;(function(){for(var f=a.concat(b),g=[],k={},h=0,m=f.length;h<m;++h){var l=f[h],r=l[3];if(r)for(var C=r.length;0<=--C;)d[r.charAt(C)]=l;l=l[1];r=""+l;k.hasOwnProperty(r)||(g.push(l),k[r]=null)}g.push(/[\0-\uffff]/);e=c(g)})();var f=b.length,k=function(a){var c=a.source,h=a.basePos,m=[h,"pln"],l=0;c=c.match(e)||[];for(var w={},r=0,C=c.length;r<C;++r){var n=c[r],v=w[n],F=void 0;if("string"===typeof v)var B=!1;else{var D=d[n.charAt(0)];if(D)F=n.match(D[1]),v=D[0];else{for(B=0;B<f;++B)if(D=b[B],F=
n.match(D[1])){v=D[0];break}F||(v="pln")}!(B=5<=v.length&&"lang-"===v.substring(0,5))||F&&"string"===typeof F[1]||(B=!1,v="src");B||(w[n]=v)}D=l;l+=n.length;if(B){B=F[1];var x=n.indexOf(B),M=x+B.length;F[2]&&(M=n.length-F[2].length,x=M-B.length);v=v.substring(5);g(h+D,n.substring(0,x),k,m);g(h+D+x,B,q(v,B),m);g(h+D+M,n.substring(M),k,m)}else m.push(h+D,v)}a.decorations=m};return k}function f(a){var b=[],c=[];a.tripleQuotedStrings?b.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):a.multiLineStrings?b.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):b.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);a.verbatimStrings&&c.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var d=a.hashComments;d&&(a.cStyleComments?(1<d?b.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):b.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),c.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):b.push(["com",/^#[^\r\n]*/,null,"#"]));a.cStyleComments&&(c.push(["com",/^\/\/[^\r\n]*/,null]),c.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));a.regexLiterals&&c.push(["lang-regex",new RegExp("^"+K+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);a=a.keywords.replace(/^\s+|\s+$/g,"");a.length&&c.push(["kwd",new RegExp("^(?:"+a.replace(/\s+/g,"|")+
")\\b"),null]);b.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);c.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return e(b,c)}function l(b){function c(b){if(b>O){u&&u!==p&&(l.push("</span>"),u=null);!u&&p&&(u=p,l.push('<span class="',u,'">'));var c=a(C(e.substring(O,b))).replace(y?v:n,"$1&#160;");
y=t.test(c);l.push(c.replace(q,A));O=b}}var e=b.source,f=b.extractedTags,g=b.decorations,h=b.numberLines,k=b.sourceNode,l=[],O=0,u=null,p=null,w=0,r=0,C=d(window.PR_TAB_WIDTH),n=/([\r\n ]) /g,v=/(^| ) /gm,q=/\r\n?|\n/g,t=/[ \r\n]$/,y=!0,x=window._pr_isIE6();k=x?k&&"PRE"===k.tagName?6===x?"&#160;\r\n":7===x?"&#160;<br />\r":8===x?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(h){var z=[];for(x=0;10>x;++x)z[x]=k+'</li><li class="L'+x+'">';var E="number"===typeof h?h-1:0;l.push('<ol class="linenums"><li class="L',
E%10,'"');E&&l.push(' value="',E+1,'"');l.push(">");var A=function(){var a=z[++E%10];return u?"</span>"+a+'<span class="'+u+'">':a}}else A=k;for(;;)if(k=w<f.length?r<g.length?f[w]<=g[r]:!0:!1)c(f[w]),u&&(l.push("</span>"),u=null),l.push(f[w+1]),w+=2;else if(r<g.length)c(g[r]),p=g[r+1],r+=2;else break;c(e.length);u&&l.push("</span>");h&&l.push("</li></ol>");b.prettyPrintedHtml=l.join("")}function h(a,b){for(var c=b.length;0<=--c;){var d=b[c];N.hasOwnProperty(d)?"console"in window&&console.warn("cannot override language handler %s",
d):N[d]=a}}function q(a,b){a&&N.hasOwnProperty(a)||(a=/^\s*</.test(b)?"default-markup":"default-code");return N[a]}function t(a){var b=a.sourceCodeHtml,c=a.langExtension;a.prettyPrintedHtml=b;try{var d=b.match(U);b=[];var e=0,f=[];if(d)for(var g=0,h=d.length;g<h;++g){var k=d[g];if(1<k.length&&"<"===k.charAt(0)){if(!V.test(k))if(W.test(k))b.push(k.substring(9,k.length-3)),e+=k.length-12;else if(X.test(k))b.push("\n"),++e;else if(0<=k.indexOf("nocode")&&k.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var u=k.match(Q)[2],p=1;var w=g+1;a:for(;w<h;++w){var r=d[w].match(Q);if(r&&r[2]===u)if("/"===r[1]){if(0===--p)break a}else++p}w<h?(f.push(e,d.slice(g,w+1).join("")),g=w):f.push(e,k)}else f.push(e,k)}else{p=k;var C=p.indexOf("&");if(0>C)var n=p;else{for(--C;0<=(C=p.indexOf("&#",C+1));){var v=p.indexOf(";",C);if(0<=v){var t=p.substring(C+3,v),y=10;t&&"x"===t.charAt(0)&&(t=t.substring(1),y=16);var z=parseInt(t,y);isNaN(z)||(p=p.substring(0,
C)+String.fromCharCode(z)+p.substring(v+1))}}n=p.replace(L,"<").replace(R,">").replace(S,"'").replace(T,'"').replace(Y," ").replace(Z,"&")}b.push(n);e+=n.length}}var x={source:b.join(""),tags:f};var A=x.source;a.source=A;a.basePos=0;a.extractedTags=x.tags;q(c,A)(a);l(a)}catch(E){"console"in window&&console.log(E&&E.stack?E.stack:E)}}function y(a,b,c){a={sourceCodeHtml:a,langExtension:b,numberLines:c};t(a);return a.prettyPrintedHtml}function z(c){function d(){for(var e=window.PR_SHOULD_USE_CONTINUATION?
l.now()+250:Infinity;q<f.length&&l.now()<e;q++){var g=f[q];if(g.className&&0<=g.className.indexOf("prettyprint")){var h=g.className.match(/\blang-(\w+)\b/);h&&(h=h[1]);for(var k=!1,n=g.parentNode;n;n=n.parentNode)if(("pre"===n.tagName||"code"===n.tagName||"xmp"===n.tagName)&&n.className&&0<=n.className.indexOf("prettyprint")){k=!0;break}if(!k){n=g;null===P&&(k=document.createElement("PRE"),k.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),P=!/</.test(k.innerHTML));
if(P)if(k=n.innerHTML,"XMP"===n.tagName)k=a(k);else{if("PRE"!==n.tagName&&aa.test(k)){var m="";n.currentStyle?m=n.currentStyle.whiteSpace:window.getComputedStyle&&(m=window.getComputedStyle(n,null).whiteSpace);n=!m||"pre"===m}else n=!0;n||(k=k.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{k=[];for(n=n.firstChild;n;n=n.nextSibling)b(n,k);k=k.join("")}k=k.replace(/(?:\r\n?|\n)$/,"");n=g.className.match(/\blinenums\b(?::(\d+))?/);u={sourceCodeHtml:k,langExtension:h,sourceNode:g,
numberLines:n?n[1]&&n[1].length?+n[1]:!0:!1};t(u);if(g=u.prettyPrintedHtml)if(h=u.sourceNode,"XMP"===h.tagName){k=document.createElement("PRE");for(n=0;n<h.attributes.length;++n)if(m=h.attributes[n],m.specified){var y=m.name.toLowerCase();"class"===y?k.className=m.value:k.setAttribute(m.name,m.value)}k.innerHTML=g;h.parentNode.replaceChild(k,h)}else h.innerHTML=g}}}q<f.length?setTimeout(d,250):c&&c()}for(var e=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
f=[],g=0;g<e.length;++g)for(var h=0,k=e[g].length;h<k;++h)f.push(e[g][h]);e=null;var l=Date;l.now||(l={now:function(){return(new Date).getTime()}});var q=0,u;d()}var K=function(){for(var a="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),b="(?:^^|[+-]",c=0;c<a.length;++c)b+="|"+a[c].replace(/([^=<>:&a-z])/g,"\\$1");return b+=
")\\s*"}(),G=/&/g,H=/</g,I=/>/g,A=/"/g,L=/&lt;/g,R=/&gt;/g,S=/&apos;/g,T=/&quot;/g,Z=/&amp;/g,Y=/&nbsp;/g,aa=/[\r\n]/g,P=null,U=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,V=/^\x3c!--/,W=/^<!\[CDATA\[/,X=/^<br\b/i,Q=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ba=f({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),N={};h(ba,["default-code"]);h(e([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));h(e([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);h(e([],[["atv",/^[\s\S]+/]]),["uq.val"]);h(f({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));h(f({keywords:"null true false"}),["json"]);h(f({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);h(f({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);h(f({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);h(f({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);h(f({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);h(f({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);h(f({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);h(f({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);h(e([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=y;window.prettyPrint=z;window.PR={combinePrefixPatterns:c,createSimpleLexer:e,registerLangHandler:h,
sourceDecorator:f,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);
